=== dhfbk/InMezzoraDataset/xml-complete/unicum.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT trascriptions (teiHeader,speech)>
<!ATTLIST trascriptions
  xmlns CDATA #FIXED ''>

<!ELEMENT teiHeader (recording)>
<!ATTLIST teiHeader
  xmlns CDATA #FIXED ''>

<!ELEMENT speech (u)+>
<!ATTLIST speech
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED>

<!ELEMENT recording (equipment,broadcast)>
<!ATTLIST recording
  xmlns CDATA #FIXED ''
  dur NMTOKEN #REQUIRED
  type NMTOKEN #REQUIRED>

<!ELEMENT u (#PCDATA|del|vocal)*>
<!ATTLIST u
  xmlns CDATA #FIXED ''
  gender NMTOKEN #REQUIRED
  role CDATA #REQUIRED
  trans NMTOKEN #IMPLIED
  who CDATA #REQUIRED>

<!ELEMENT equipment (p)>
<!ATTLIST equipment
  xmlns CDATA #FIXED ''>

<!ELEMENT broadcast (bibl)>
<!ATTLIST broadcast
  xmlns CDATA #FIXED ''>

<!ELEMENT del (#PCDATA)>
<!ATTLIST del
  xmlns CDATA #FIXED ''
  type NMTOKEN #REQUIRED>

<!ELEMENT vocal EMPTY>
<!ATTLIST vocal
  xmlns CDATA #FIXED ''
  desc NMTOKEN #REQUIRED
  dur NMTOKEN #IMPLIED
  type NMTOKEN #REQUIRED>

<!ELEMENT p (#PCDATA)>
<!ATTLIST p
  xmlns CDATA #FIXED ''>

<!ELEMENT bibl (title,author,respStmt+,series,date)>
<!ATTLIST bibl
  xmlns CDATA #FIXED ''>

<!ELEMENT author (#PCDATA)>
<!ATTLIST author
  xmlns CDATA #FIXED ''>

<!ELEMENT respStmt (resp,name)>
<!ATTLIST respStmt
  xmlns CDATA #FIXED ''>

<!ELEMENT series (title)>
<!ATTLIST series
  xmlns CDATA #FIXED ''>

<!ELEMENT date (#PCDATA)>
<!ATTLIST date
  xmlns CDATA #FIXED ''
  when NMTOKEN #REQUIRED>

<!ELEMENT resp (#PCDATA)>
<!ATTLIST resp
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  xmlns CDATA #FIXED ''>

=== dhfbk/InMezzoraDataset/xml-complete/30+10_12_17.xml
<?xml version= "1.0" encoding= "UTF-8"?>
<!DOCTYPE trascriptions SYSTEM "unicum.dtd">
<trascriptions>
    <teiHeader>
	<recording type="video" dur="01:03:37">
		<equipment>
			<p>Recorded from http://www.raiplay.it/video/2017/12/12-h-in-piu-7d6c8a44-85d9-42c8-be9c-18c841d728e5.html</p>
		</equipment>
	<broadcast>
		<bibl>
			<title>political talk-show</title>
			<author>Rai 3</author>
			<respStmt>
				<resp>interviewer</resp>
				<name>Lucia Annunziata</name>
			</respStmt>
			<respStmt>
				<resp>interviewee</resp>
				<name>Angelino Alfano, Mario Calabresi, Giulio Tremonti, Matteo Orfini</name>
			</respStmt>
			<series>
				<title>In mezz'ora in più</title>
			</series>
				<date when="2018-12-17">17 December 2017</date>
		</bibl>
	</broadcast>
	</recording>
	</teiHeader>

<speech id="012">
<u who="Lucia Annunziata" role="host" gender="f"><vocal type="semi-lexical" desc="ehmm"/>Buongiorno e bentornati a "Mezz'ora in più". Vorrei intanto<vocal type="semi-lexical" desc="ehmm"/>salutare l'ospite di questa prima serata, lo conoscete sicuramente. È sempre venuto da noi regolarmente. Buongiorno Ministro Angelino Alfano.</u>
<u who="Angelino Alfano" role="Minister of the foreign business and of the international cooperation" gender="m">Buongiorno a voi!</u>
<u who="Lucia Annunziata" role="host" gender="f">Che è diventato in questo momento estremamente popolare perché, come si diceva prima. È un Ministro che<vocal type="semi-lexical" desc="ahh"/>come dire. È in carica da ben 4 Ministeri che improvvisamente dice: me ne vado e mi troverò un lavoro. Un, come dire, una cosa molto, come dire, seria come<vocal type="semi-lexical" desc="ehmm" dur="2s"/>venendo oggi da una classe politica piuttosto screditata. Però se mi permette, Ministro, volevo un attimo salutare una persona, che è un mio caro amico. È una persona molto importante per i media italiani.<vocal type="semi-lexical" desc="ah"/>Mario Calabresi. Buongiorno! Il direttore di Repubblica, ci senti, Mario?</u>
<u who="Mario Calabresi" role="Head editor La Repubblica" gender="m">Buongiorno a voi!</u>
<u who="Lucia Annunziata" role="host" gender="f">Buongiorno! Intanto volevamo approfittare di questa trasmissione per portare anche la nostra solidarietà all'assalto che c'è stato nei confronti della sede di Repubblica e dell'Espresso il 16 dicembre. Ricordiamo i fatti: c'è stata una rivendicazione di Forza Nuova, di un blitz di un gruppo mascherato<vocal type="semi-lexical" desc="ehmm"/>che ha acceso fumogeni e letto un proclama. La cosa forse più, Mario<vocal type="semi-lexical" desc="ehmm"/>più brutta di quella giornata, vediamo delle immagini, È stato poi la rivendicazione su Facebook in cui diceva<vocal type="semi-lexical" desc="ehmm"/>: "Torce accese per illuminare la verità contro le menzogne dei pennivendoli di regime e maschere sul volto". Ma finiva: "Oggi è stato solo il primo attacco contro chi diffonde il verbo immigrazionista, serve gli interessi di ONG, COOP e mafie varie". Domani ci sarà<del type="falseStart">una</del>un sit-in sotto Repubblica e siamo qui per lanciare anche questo sit-in e ringraziamo tutti. Organizzato da varie organizzazioni: Federazione Internazionale della Stampa, Articolo 21, l'Ordine dei Giornalisti, Lusicrai, Emergency, CGIL, ANPI e i comitati di redazione dei<del type="falseStart">maggior</del>di quasi tutti i maggiori giornali: Il Fatto, Il Corriere, L'Espresso, L'Huffington Post eccetera. Dunque, Mario<pause dur="1.0"/>voi avete sposato una linea <pause dur="1.0"/>di denuncia, dicendo siete stati tra i primi a dire: "Sta salendo davvero un'onda lunga". Molti però contestano anche di fronte a questi fatti, che ci sia un'esagerazione da parte, diciamo, delle forze democratiche nella lettura di questi fenomeni. Per te è un'esagerazione? O le prove di questi giorni, gli episodi di questi giorni prova che c'è effettivamente un pericolo più grande di quel che si pensi.</u>
<u who="Mario Calabresi" role="Head editor La Repubblica" gender="m">No, io non penso naturalmente che ci sia un'esagerazione. A quelli che dicono:<vocal type="semi-lexical" desc="ehmm"/>"Va behm, ma non c'è un ritorno di fascismo".<vocal type="semi-lexical" desc="ehm"/>È un modo di derubricare il dibattito, di mandarlo in vacca. È evidente che non c'è un fascismo. Viviamo in democrazia, le nostre istituzioni, per quanto spesso fragili e criticabili, ci<del type="repetition">sono sono</del> salde. Quello che c'è però è un clima che sta salendo. Ed è un clima di violenze leggere, di intimidazione, razzismi. <del type="repetition">Lo vediamo lo vediamo</del>a ripetizione. E vediamo che sta passando in una sorta di<vocal type="semi-lexical" desc="ehmm"/>viene sminuito o viene banalizzato, viene sopportato. Quando si ripetono gli episodi in cui ci sono aggressioni a migranti, quando si chiude la bocca a chi cerca di aiutarli, quando <vocal type="semi-lexical" desc="ehmm"/>vengono fatte le ronde o i blocchi per impedire che una casa popolare, un alloggio venga dato a una famiglia italiana di origine straniera, ecco tutto questo se viene derubricato e lasciato passare, secondo me è molto grave. Perché continua a crescere, noi cosa abbiamo fatto? Non siamo partiti<del type="falseStart">da</del>delle fisime. Abbiamo fatto una serie di inchieste in cui abbiamo raccontato, per esempio<pause dur="1.0"/>i legami tra criminalità organizzata e gruppi neofascisti come succede a Ostia e in alcune periferie romane. <del type="repetition">Abbiamo messo il, abbiamo messo il</del>il focus su, per esempio, sulle società, sui soldi, per esempio, di Forza Nuova. Cosa che ci ha attirato questa manifestazione degli strali di fiore. Abbiamo messo in evidenza come, nella rete per esempio, sia un fiorire di parole d'ordine e di incitamento alla violenza che viene fatto molto sui giovani per esempio nelle scuole, nelle università. Allora tutto questo, secondo me, è da prendere come estrema attenzione. E c'è invece un gioco in Italia<vocal type="semi-lexical" desc="ehm"/>che viene fatto per chi vuole prendersi 4 voti, 4 click se è un sito internet o vendere 4 copie in più di giornale, che schiaccia gli occhi ai razzismi, ci gioca, sminuisce le cose, tendere a dire: "Ma no! Sono ragazzate". Ma sono ragazzate perché sanno che si possono permettere di dire questo perché c'è un clima che purtroppo si allarga su cui vogliono lucrare.</u>
<u who="Lucia Annunziata" role="host" gender="f"><vocal type="semi-lexical" desc="ehmm"/>Mario, c'è però anche chi dice, aggiungo alle varie critiche, che questo anti-fascismo di ritorno serve benissimo, come è successo poi ieri a Como, in fondo a dare un'unità di facciata formale al centro-sinistra sotto le elezioni<vocal type="semi-lexical" desc="ehmm"/>che è un centro-sinistra che altrimenti non è riunito da quasi nessun altro argomento.</u>
<u who="Mario Calabresi" role="Head editor La Repubblica" gender="m">Bah, mi sembra un'obiezione un po' ridicola in questo senso. Che non è che siccome per un giorno, per qualche ora le varie anime della sinistra si sono ritrovate a Como, si sono unite. Mi pare che lo scenario di qualunque giorno, non so l'intervista che c'è oggi di Renzi su Repubblica racconta con chiarezza che invece uniti non sono per nulla. Per cui...<vocal type="semi-lexical" desc="ehmm"/>È ridicolo dire questo. Come quelli che dicono: "Ah però ci sono anche storicamente le violenze dell'estrema sinistra, i gruppi anarchici eccetera eccetera". È vero, ci sono anche quelle. Il punto è che<vocal type="semi-lexical" desc="ehmm"/>chi ha sempre denunciato quelle, oggi deve, come il sottoscritto, si può permettere di dire: attenzione perché c'è un altro fenomeno che non può essere sottovalutato.</u>
<u who="Lucia Annunziata" role="host" gender="f">Va bene! Ti ringrazio, Mario. Intanto<vocal type="semi-lexical" desc="ehm"/>rilanciamo l'appuntamento di domani.</u>
<u trans="overlap" who="#Mario Calabresi" role="Head editor La Repubblica" gender="m">Grazie a voi!</u>
<u who="Lucia Annunziata" role="host" gender="f">Alle 15.30 organizzato da giornalisti, comitati di redazione di grandi giornali, organizzazioni varie. Sit-in sotto<vocal type="semi-lexical" desc="ehmm"/>Repubblica e gruppo Espresso alle 15.30. Diamo anche l'indirizzo, Cristoforo Colombo 90. Tanto chi vi vuole venire ad aggredire, l'indirizzo come s'è visto ce l'ha.</u>
<u who="Mario Calabresi" role="Head editor La Repubblica" gender="m">Sì, sa già dove stiamo chi vuol dar fastidio.</u>
<u who="Lucia Annunziata" role="host" gender="f">Esatto! Arrivederci allora!<vocal type="semi-lexical" desc="ehmm"/>Buongiorno Ministro! Intanto.</u>
<u who="Mario Calabresi" role="Head editor La Repubblica" gender="m">A voi, Buonpomeriggio!</u>
<u who="Lucia Annunziata" role="host" gender="f">Grazie!<vocal type="semi-lexical" desc="ehm"/>volevo dirle<vocal type="semi-lexical" desc="ehm"/>ovviamente io sono molto interessata alle sue decisioni, però, voglio dire, lei che è un Ministro che ha lavorato a destra, ha lavorato a sinistra cioè in diversi Governi eccetera eccetera. Cosa pensa di questo, proprio delle domande che ho fatto<vocal type="semi-lexical" desc="ah"/>a Calabresi. C'è o è effettivamente un risorgere molto forte<vocal type="semi-lexical" desc="ehm"/>del fascismo tradizionale anche piuttosto radicale all'interno, per esempio, del centro-destra che lei conosce molto bene. C'È un'anima?</u>
